services:
  db:
    image: postgres:17
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: aserturik
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: nodepg
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  app:
    build: .
    container_name: node_app
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DB_USER: aserturik
      DB_PASSWORD: mypassword
      DB_HOST: db 
      DB_PORT: 5432
      DB_DATABASE: nodepg
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
